version: "3.6"

services:
    webserver:
        image: nginx:alpine
        container_name: coding-webserver
        working_dir: /application
        volumes:
            - .:/application
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php-coding
        ports:
            - "18030:80"

    php-coding:
        environment:
            - PHP_IDE_CONFIG=serverName=localhost
        container_name: coding-php
        build:
            context: ./
            dockerfile: docker/php/Dockerfile
            cache_from:
                - ./docker/php
        depends_on:
            - mysql
        links:
            - mysql
        volumes:
            - ./:/application:rw,cached
            - /usr/local/lib

    mysql:
        image: mysql:5.7
        container_name: mysql
        working_dir: /application
        command: mysqld --sql_mode=''
        volumes:
            - mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=coding
            - MYSQL_USER=coding
            - MYSQL_PASSWORD=password
            - explicit_defaults_for_timestamp=1
        ports:
            - "18032:3306"
        expose:
            - 18032
networks:
    default:
        external:
            name: "coding"
volumes:
    mysql: {}
